zappa_boilerplate/models.py
# import your models here
import zappa_boilerplate.user.models

zappa_boilerplate/user/models.py
import bcrypt
import datetime
import flask
from flask_login import UserMixin
import sqlalchemy

from zappa_boilerplate.database import Base


class User(Base, UserMixin):

    __tablename__ = 'users'
    id = sqlalchemy.Column(sqlalchemy.Integer, primary_key=True)
    username = sqlalchemy.Column(sqlalchemy.String(80), unique=True, nullable=False)
    email = sqlalchemy.Column(sqlalchemy.String(80), unique=True, nullable=False)

    password = sqlalchemy.Column(sqlalchemy.String(128), nullable=True)  # the hashed password
    created_at = sqlalchemy.Column(sqlalchemy.DateTime, nullable=False, default=datetime.datetime.utcnow)

    def __init__(self, username, email, password):
        self.username = username
        self.email = email
        self.set_password(password)

    @staticmethod
    def create(session, username, email, password):
        user = User(username, email, password)
        session.add(user)
        session.flush()
        return user

    @classmethod
    def get_by_id(cls, session, user_id):
        if any(
            (isinstance(user_id, str) and user_id.isdigit(),
             isinstance(user_id, (int, float))),
        ):
            return session.query(cls).filter(cls.id == user_id).first()
        return None

    def set_password(self, password):
        self.password = bcrypt.hashpw(password.encode('utf-8'),
                                      bcrypt.gensalt(flask.current_app.config['BCRYPT_LOG_ROUNDS'])).decode('utf-8')

    def check_password(self, value):
        return bcrypt.checkpw(value.encode('utf-8'), self.password.encode('utf-8'))

    def __repr__(self):
        return '<User({username!r})>'.format(username=self.username)

zappa_boilerplate/user/forms.py
# -*- coding: utf-8 -*-
from zappa_boilerplate.database import db_session
from flask_wtf import Form
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from .models import User


class RegisterForm(Form):
    username = StringField('Username',
                           validators=[DataRequired(), Length(min=3, max=25)])
    email = StringField('Email',
                        validators=[DataRequired(), Email(), Length(min=6, max=40)])
    password = PasswordField('Password',
                             validators=[DataRequired(), Length(min=6, max=40)])
    confirm = PasswordField('Verify password',
                            [DataRequired(), EqualTo('password', message='Passwords must match')])

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = db_session.query(User).filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append("Username already registered")
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append("Email already registered")
            return False
        return True

zappa_boilerplate/app.py
# -*- coding: utf-8 -*-
"""The app module, containing the app factory function."""
from flask import Flask, render_template

from zappa_boilerplate.settings import Local
from zappa_boilerplate.extensions import (
    db,
    login_manager,
    migrate,
)
from zappa_boilerplate.database import Base, init_engine
from zappa_boilerplate.assets import assets
from zappa_boilerplate import public, user

def create_app(config_object=Local):
    """
    An application factory, as explained here:
    http://flask.pocoo.org/docs/patterns/appfactories/

    :param config_object: The configuration object to use.
    """
    app = Flask(__name__.split('.')[0])
    app.config.from_object(config_object)
    init_engine(app.config['SQLALCHEMY_DATABASE_URI'])
    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    return app


def register_extensions(app):
    assets.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    migrate.init_app(app, Base)
    return None


def register_blueprints(app):
    app.register_blueprint(public.views.blueprint)
    app.register_blueprint(user.views.blueprint)
    return None


def register_errorhandlers(app):
    def render_error(error):
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)
        return render_template("{0}.html".format(error_code)), error_code
    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)
    return None

zappa_boilerplate/user/__init__.py
# -*- coding: utf-8 -*-
"""The users module."""

from . import views

zappa_boilerplate/user/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template
from flask_login import login_required

blueprint = Blueprint("user", __name__, url_prefix='/users', static_folder="../static")


@blueprint.route("/")
@login_required
def members():
    return render_template("users/members.html")

zappa_boilerplate/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

zappa_boilerplate/templates/footer.html
<footer>
    <small>
        <ul class="company">
            <li>© 2021 Daniel Newman</li>

        </ul>
    </small>
    <ul class="footer-nav">

        <li>
            <a href="https://github.com/dtnewman/zappa_boilerplate">
                <button type="button" class="btn btn-outline-gray">Checkout on GitHub <i class="fa fa-lg fa-github"></i></button>
            </a>
        </li>
    </ul>
</footer>

zappa_boilerplate/templates/layout.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>{% block page_title %}Zappa App{% endblock %}</title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  {% assets "css_all" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
  {% endassets %}

  {% block css %}{% endblock %}

</head>
<body class="{% block body_class %}{% endblock %}">
{% block body %}
{% with form=form  %}
{% include "nav.html" %}
{% endwith %}

<header>{% block header %}{% endblock %}</header>
<div class="{% block content_class %}container{% endblock content_class %}">

  <div role="main">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="row">
      <div class="col-md-12">
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
         {{message}}
        </div><!-- end .alert -->
        {% endfor %}
      </div><!-- end col-md -->
    </div><!-- end row -->
        {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}
  </div>

</div><!-- end container -->

{% include "footer.html" %}

<!-- JavaScript at the bottom for fast page loading -->
{% assets "js_all" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% block js %}{% endblock %}
<!-- end scripts -->
{% endblock %}
</body>
</html>

zappa_boilerplate/templates/nav.html
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('public.home') }}">Zappa Boilerplate</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li {% if request.path=="/" %}class="active"{% endif %}><a href="{{ url_for('public.home') }}">Home</a>
                </li>
                <li {% if request.path=="/about" %}class="active"{% endif %}><a href="{{ url_for('public.about') }}">About</a>
                </li>
            </ul>

            {% if current_user and current_user.is_authenticated %}
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <p class="navbar-text"><a class="navbar-link" href="{{ url_for('user.members') }}">Logged in
                            as {{ current_user.username }}</a></p>
                    </li>
                    <li><a class="navbar-link" href="{{ url_for('public.logout') }}"><i class="fa fa-sign-out"></i></a>
                    </li>

                </ul>
            {% elif form %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('public.register') }}">Create account</a></li>
                </ul>
                <form id="loginForm" method="POST" class="navbar-form form-inline navbar-right"
                      action="{{ url_for('public.home') }}" role="login">
                    {{ form.hidden_tag() }}
                    <div class="form-group">
                        {{ form.username(placeholder="Username", class_="form-control") }}
                        {{ form.password(placeholder="Password", class_="form-control") }}
                    </div>

                    <button type="submit" class="btn btn-default">Log in</button>
                </form>
            {% endif %}
        </div>
    </div>
</nav>